version: '3.8'

services:
  # Ollama backend service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - app-network
    restart: unless-stopped
    # Uncomment below to enable GPU support (NVIDIA)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Open WebUI (formerly Ollama WebUI)
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3002:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your-secret-key-here-change-this
      - WEBUI_NAME=Ollama Web UI
      - ENABLE_SIGNUP=true
      # Database configuration
      - DATABASE_URL=sqlite:////app/backend/data/webui.db
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - app-network
    restart: unless-stopped

  # n8n workflow automation
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_ENCRYPTION_KEY=your-encryption-key-change-this
      # Basic auth (optional - remove if not needed)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme
      # Database - using SQLite for simplicity
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      # Executions
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-files:/files
    networks:
      - app-network
    restart: unless-stopped

  # PostgreSQL database (optional - for production use)
  # Uncomment if you want to use PostgreSQL instead of SQLite for n8n
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: postgres
  #   environment:
  #     - POSTGRES_USER=n8n
  #     - POSTGRES_PASSWORD=n8n_password_change_this
  #     - POSTGRES_DB=n8n
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U n8n"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

volumes:
  ollama_data:
    driver: local
  open_webui_data:
    driver: local
  n8n_data:
    driver: local
  # postgres_data:
  #   driver: local

networks:
  app-network:
    driver: bridge