version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nginx-ssl-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/common:/etc/nginx/common:ro
      - ./html:/usr/share/nginx/html:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./ssl/production/dhparam.pem:/etc/nginx/ssl/production/dhparam.pem:ro
    restart: unless-stopped
    environment:
      - NGINX_ENV=production
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"