FROM nginx:alpine

# Copy nginx configurations
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/ssl.conf /etc/nginx/ssl.conf

# Copy HTML content
COPY html/ /usr/share/nginx/html/

# Create directories for Let's Encrypt
RUN mkdir -p /var/www/certbot

# Copy common configurations
COPY nginx/common/ /etc/nginx/common/

# Remove default nginx config
RUN rm -f /etc/nginx/conf.d/default.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]