# Common SSL parameters content here
# Common SSL parameters for both dev and prod

# SSL protocols
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;

# SSL session caching
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;

# Disable SSL session tickets
ssl_session_tickets off;

# SSL buffer size (can improve performance)
ssl_buffer_size 8k;